### ISSUE TITLE
JSONDecodeError: Expecting value during connection in Quotex API

### ISSUE THREAD

**Issue by omkar777x** [cleitonleonel/pyquotex#38]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\omkar\OneDrive\Desktop\pyquotex-master\pyquotex-master> python3 app.py get_realtime_candle
██████╗ ██╗   ██╗ ██████╗ ██╗   ██╗ ██████╗ ████████╗███████╗██╗  ██╗
██╔══██╗╚██╗ ██╔╝██╔═══██╗██║   ██║██╔═══██╗╚══██╔══╝██╔════╝╚██╗██╔╝
██████╔╝ ╚████╔╝ ██║   ██║██║   ██║██║   ██║   ██║   █████╗   ╚███╔╝
██╔═══╝   ╚██╔╝  ██║▄▄ ██║██║   ██║██║   ██║   ██║   ██╔══╝   ██╔██╗
██║        ██║   ╚██████╔╝╚██████╔╝╚██████╔╝   ██║   ███████╗██╔╝ ██╗
╚═╝        ╚═╝    ╚══▀▀═╝  ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝╚═╝  ╚═╝

        author: Cleiton Leonel Creton versão: 1.0.0

Use com moderação, pois gerenciamento é tudo!
suporte: cleiton.leonel@gmail.com ou +55 (27) 9 9577-2291

Quotex Connecting...
Traceback (most recent call last):
  File "C:\Users\mycomp\OneDrive\Desktop\pyquotex-master\pyquotex-master\app.py", line 518, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\mycomp\OneDrive\Desktop\pyquotex-master\pyquotex-master\app.py", line 512, in main
    await execute(option)
  File "C:\Users\mycomp\OneDrive\Desktop\pyquotex-master\pyquotex-master\app.py", line 482, in execute
    return await get_realtime_candle()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mycomp\OneDrive\Desktop\pyquotex-master\pyquotex-master\app.py", line 405, in get_realtime_candle
    check_connect, message = await client.connect()
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mycomp\OneDrive\Desktop\pyquotex-master\pyquotex-master\quotexapi\stable_api.py", line 217, in connect
    check, reason = await self.api.connect(self.account_is_demo)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mycomp\OneDrive\Desktop\pyquotex-master\pyquotex-master\quotexapi\api.py", line 393, in connect
    check_websocket, websocket_reason = await self.start_websocket()
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mycomp\OneDrive\Desktop\pyquotex-master\pyquotex-master\quotexapi\api.py", line 336, in start_websocket
    await self.authenticate()
  File "C:\Users\mycomp\OneDrive\Desktop\pyquotex-master\pyquotex-master\quotexapi\api.py", line 319, in authenticate
    status, message = await self.login(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\mycomp\OneDrive\Desktop\pyquotex-master\pyquotex-master\quotexapi\http\login.py", line 19, in __call__
    return await self.get_cookies_and_ssid()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mycomp\OneDrive\Desktop\pyquotex-master\pyquotex-master\quotexapi\http\qxbroker.py", line 168, in get_cookies_and_ssid
    await self.main()
  File "C:\Users\mycomp\OneDrive\Desktop\pyquotex-master\pyquotex-master\quotexapi\http\qxbroker.py", line 165, in main
    await self.run(playwright)
  File "C:\Users\mycomp\OneDrive\Desktop\pyquotex-master\pyquotex-master\quotexapi\http\qxbroker.py", line 139, in run
    token = json.loads(match).get("token")
            ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
PS C:\Users\mycomp\OneDrive\Desktop\pyquotex-master\pyquotex-master>

**Comment by cleitonleonel** [comment]
> token = json.loads(match).get("token")

This error occurs because the login was not successful and that is why there is no session token.

**Comment by omkar777x** [comment]
ok thanks for explaning acctually my temp qoutex account got banned so i created new so it started working again on diffrent account but after sometimes this started to show up but not it works fine
