### ISSUE TITLE
Error on start app

### ISSUE THREAD

**Issue by DevHerles** [cleitonleonel/pyquotex#41]
```bash
❯ python3.10 app.py
Traceback (most recent call last):
  File "/home/herles/asf/devherles/pyquotex/app.py", line 13, in <module>
    from quotexapi.config import (
  File "/home/herles/asf/devherles/pyquotex/quotexapi/config.py", line 27, in <module>
    password = config.get("settings", "password")
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/configparser.py", line 801, in get
    return self._interpolation.before_get(self, section, option, value,
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/configparser.py", line 396, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/configparser.py", line 443, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%'

```

**Comment by cleitonleonel** [comment]
> ```shell
> ❯ python3.10 app.py
> Traceback (most recent call last):
>   File "/home/herles/asf/devherles/pyquotex/app.py", line 13, in <module>
>     from quotexapi.config import (
>   File "/home/herles/asf/devherles/pyquotex/quotexapi/config.py", line 27, in <module>
>     password = config.get("settings", "password")
>   File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/configparser.py", line 801, in get
>     return self._interpolation.before_get(self, section, option, value,
>   File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/configparser.py", line 396, in before_get
>     self._interpolate_some(parser, option, L, value, section, defaults, 1)
>   File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/configparser.py", line 443, in _interpolate_some
>     raise InterpolationSyntaxError(
> configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%'
> ```

How is your config.ini file?

**Comment by DevHerles** [comment]
Based on the README file and after installing the libraries,  I executed the following:

```python
pyquotex on  master via 🐍 v3.12.3
❯ /home/herles/asf/devherles/pyquotex/.venv/bin/python /home/herles/asf/devherles/pyquotex/app.py
Insira o e-mail da conta: myquotexemailaccount@gmail.com
Insira a senha da conta: myrealquotexpassword
Insira a senha da conta de e-mail: myrealquotexpassword
Insira um caminho para o profile do browser: browser
Traceback (most recent call last):
  File "/home/herles/asf/devherles/pyquotex/app.py", line 13, in <module>
    from quotexapi.config import (
  File "/home/herles/asf/devherles/pyquotex/quotexapi/config.py", line 27, in <module>
    password = config.get("settings", "password")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/configparser.py", line 777, in get
    return self._interpolation.before_get(self, section, option, value,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/configparser.py", line 367, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.12/configparser.py", line 414, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%'
```

Are you referring to this init file: `/home/herles/asf/devherles/pyquotex/settings/config.ini`? Here is the content:

```ini
[settings]
email=myquotexemailaccount@gmail.com
password=myrealquotexpassword
email_pass=myrealquotexpassword
user_data_dir=browser
```

**Comment by DevHerles** [comment]
I identified the issue: My password contained the `%` character, which caused the problem. After updating my password to one without any special characters, everything started working perfectly.

It seems like `config.ini` settings are not being used, I just applied the correct values in the following:

```python
client = Quotex(
    email="myquotexemailaccount@gmail.com",
    password="myrealquotexpasswordwithoutstrangechars",
    headless=True,
    on_pin_code=on_pin_code,
)
```

After making these changes, I ran:
```bash
quotexpy on  main [?] is 📦 v1.40.7 via 🐍 v3.10.15 (.venv)
❯ python3 main.py
[INFO]:  Balance:  10000.74
[INFO]:  Asset is open.
[INFO]:  Waiting for result...
[INFO]:  Loss -> Loss: 0
[INFO]:  Balance:  10044.24
[INFO]:  Exiting...
```

Everything is now functioning as expected.
